Add mirror-image transformation
membraneframework/video_compositor pull request #135
Opened 2023-09-07 15:19 UTC by wkozyra95

- Add mirror image transformation with option to flip input vertically or horizontally
- default to horizontal

2023-09-07 15:33 UTC, wkozyra95 commented on compositor_common/src/scene/builtin_transformations.rs
> +impl Display for MirrorMode {
I had to implement custom serialization and deserizliation becuase flatten and default don't work together

2023-09-07 17:03 UTC, WojciechBarczynski requested changes

2023-09-07 17:03 UTC, WojciechBarczynski commented on compositor_render/src/transformations/builtin.rs
> +                }),
We should probably create sth like fallbacks, where each of those transformations would only specify foxed resolution or resolution of input or other similar options.

2023-09-07 17:03 UTC, WojciechBarczynski commented on compositor_render/src/transformations/builtin/mirror_image.wgsl
> +@group(1) @binding(0) var<uniform> mirror_params: MirrorParams;
Why not just u32?

2023-09-07 17:57 UTC, wkozyra95 commented on compositor_render/src/transformations/builtin/node.rs
> +        };
I think match is a lot more readable in this case

> This copy is useless. Create buffer init needs only ref

initially I had `let content` shadow original content, and forgot to remove that clone after

2023-09-07 18:02 UTC, wkozyra95 commented on compositor_render/src/transformations/builtin/params.rs
> +            }
the point of extracting it to functions is to tie binary structure to the rust type, but here we don't have a type that we can add method too. So:
- I don't think that just extracting that to function is helping with anything.
- Given the simplicity I decided that this is good enough middle ground.
- I could create separate type that wrapps MirrorMode and add appropriate method on it. I think that it's a an overkill in this case, but if you feel strongly about it I could add that wrapper type

2023-09-07 18:04 UTC, wkozyra95 commented on compositor_render/src/transformations/builtin/mirror_image.wgsl
> +@group(1) @binding(0) var<uniform> mirror_params: MirrorParams;
no reason, just my preference

2023-09-08 08:56 UTC, wkozyra95 commented on compositor_render/src/transformations/builtin/node.rs
> +        };
ok nevermind. I need that clone because I can't return borrowed value because somone needs to own that 1-element slice

2023-09-08 09:54 UTC, WojciechBarczynski approved these changes

2023-09-08 10:53 UTC, merged