Implement `V8Function`
membraneframework/video_compositor pull request #156
Opened 2023-09-12 14:20 UTC by noituri

This PR makes it possible to create and call JS functions. I intend to use this later on for retrieving canvas position

2023-09-13 09:22 UTC, wkozyra95 approved these changes

2023-09-13 09:22 UTC, wkozyra95 commented on compositor_chromium/src/v8/context.rs
> +    pub fn eval(&self, code: &str) -> Result<V8Value, V8ContextError> {
based on offline discussion this is not needed, so I would remove it.

2023-09-13 10:01 UTC, WojciechBarczynski approved these changes

2023-09-13 11:24 UTC, jerzywilczek requested changes
:crab:

2023-09-13 11:24 UTC, jerzywilczek commented on compositor_chromium/src/v8/function.rs
> +    }
If F panics, the unwinding panic will cross into C++ land, which is a big no-no. 
read [this](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) and catch the panic.

2023-09-14 09:36 UTC, jerzywilczek approved these changes
:rocket:

2023-09-14 09:40 UTC, merged