Handle unregistering web renderer
membraneframework/video_compositor pull request #247
Opened 2023-11-09 09:03 UTC by noituri

2023-11-09 09:19 UTC, jerzywilczek approved these changes
I mean it looks fine, but I might be missing something bc I don't understand the big picture

2023-11-09 09:47 UTC, WojciechBarczynski approved these changes

2023-11-15 09:18 UTC, wkozyra95 approved these changes

2023-11-15 09:21 UTC, wkozyra95 commented
after merging cherry pick that to new-api too

2023-11-30 13:10 UTC, wkozyra95 requested changes
we most likelly won't be releasing any new version for old API, so either switch this PR to v0.1 branch or rebase to new API. I don't think there is a need to fix that in the old API, so I would suggest rebasing.

2023-12-11 09:38 UTC, merged